darknet.py for MXNet-master (#1554)
* resnet.py numpy

* fix both document and a bug for RandomCrop (#1389)

* fix both document and a bug for RandomCrop

`RandomCrop` pad first and then crop, not what is said in the document or even CIFAR tutorials.

further, an error occurs with the default `pad=None`
```
>>> for i in train_data:break
... 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 450, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 450, in <listcomp>
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/data/dataset.py", line 219, in __getitem__
    return self._fn(*item)
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/data/dataset.py", line 230, in __call__
    return (self._fn(x),) + args
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/nn/basic_layers.py", line 55, in forward
    x = block(x)
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/home/neutron/.local/lib/python3.8/site-packages/gluoncv/data/transforms/block.py", line 75, in forward
    return image.random_crop(nd.array(x_pad), *self._args)[0]
UnboundLocalError: local variable 'x_pad' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neutron/.local/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 505, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
UnboundLocalError: local variable 'x_pad' referenced before assignment
```



This PR is intend to fix both the document and the BUG which caused `pad` cannot be optional.

* make pylint happy.

make pylint happy.

* happy-2

happy-2

* remove monkey patch

I just think monkey patch may goes faster than the useless switch in the forward step

* make checkers happy

* fix CI checks

* Update resnet.py

* Update resnet.py

* Update resnet.py

* bump up to 0.9 pre (#1412)

* bump up to 0.9 pre

* fix nightly build mxnet

* Update resnet.py

* fixing ci

* Revert "fixing ci"

This reverts commit d2daaa3e4cf36d9146744320d89b32dcaa569ef2.

* Update resnet.py

* fix ci checks err

* fix ci check errors

* fix ci check errors

* fix ci check errors

* fix ci check errors

* fix ci check errors

* fix ci sanity check errors

* fix ci check errors

* fix ci check errors

* fix type errors add as_nd_ndarray

* fix ci check errors

* modifying ssd.py resnet.py anchor.py

* fix sanity check errors

* fix sanity check warnings

* modifying batchify,py rcnn.py anchor.py rpn_target

* fix rpn_target.py sanity

* modify batchify.py sanity checks

* revert gluoncv/data/batchify.py to 1d84cae

* modifying batchify.py

* ssd.py nd.concat with as_np_ndarray

* ssd.py nd.concat with as_np_ndarray

* errors still exist

* fix ci check errors

* fix sanity check errors

* fix sanity check, modify matcher.py

* disable unittest of ssd

* fix test_data_transforms.py

* disable all unnecessary

* disable unnecessay tests for resnet.py

* import unittest test_nn utils_bbox metric parallel

* disable uncessary tests for resnet

* skip test_get_all_models

* disable unnecessary tests

* disable more test cases

* disable resnet_v1b tests

* fix tests bugs in test_model_zoo.py

* disable tests for resnest

* disable tests for se_resnet

* disable nasnet tests

* disable other tests

* disable more tests

* fix carelessness

* disable tests

* import unittest

* unuse as_np_ndarray()

* convert inputs to numpy ndarray

* revert all changes except resnet.py

* modifying image.py

* Numpy API: cifar danet deeplab fcn pspnet...

* commit message

* resnest for mxnet-master

* resnest for mxnet master

* remove unrelated files

* remove unrelated files

* sanity

* sanity

* sanity

* fixing error

* fix resnest

* resnext for mxnet-master

* fix test_model_zoo

* gluoncv/model_zoo/resnext.py:201:86: W0613: Unused argument 'stage_index' (unused-argument)

* Unused argument 'stage_index' (unused-argument)

* senet for mxnet-master

* mobilenet for mxnet-master

* sanity

* mobilenetv3 for mxnet master

* darknet only for mxnet master

* from .yolo import *

Co-authored-by: jinboci <cijinbo@outlook.com>
Co-authored-by: Neutron3529 <qweytr_1@163.com>
Co-authored-by: Joshua Z. Zhang <cheungchih@gmail.com>
Co-authored-by: Ubuntu <ubuntu@ip-172-31-29-176.ap-northeast-1.compute.internal>